[package]
name = "server"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cluster = {path = ".."}
ciborium = "0.2.1"
rocket = "=0.5.0-rc.4"
queues = "1.0.2"